# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

# Ensure waybar is launched
exec-once = waybar

general {
    col.active_border = rgba(f5f5f5ee) rgba(8e8e93ee) 45deg
}

decoration {
    rounding = 20

    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        ignore_opacity = true
    }

    active_opacity = 0.90
    inactive_opacity = 0.85
}

# Add layer rules to blur menus and waybar
layerrule = blur, wofi
layerrule = ignorealpha 0.5, wofi

layerrule = blur, walker
layerrule = ignorealpha 0.5, walker

layerrule = blur, waybar
layerrule = ignorealpha 0.5, waybar

layerrule = blur, swayosd
layerrule = ignorealpha 0.5, swayosd

layerrule = blur, notifications
layerrule = ignorealpha 0.5, notifications
